(()=>{
  'use strict';
  const $=id=>document.getElementById(id),views=['landing','connect','map'];
  let mapData=null,currentUser=null,selectedId=null,expanded=new Set(),openDatabaseTables=new Set(),toastTimer=null;
  let recorder=null,mediaStream=null,audioChunks=[],recordingStarted=0,recordingTimer=null,discardRecording=false,activeController=null,assistantBusy=false,settingsLoaded=false,lastFocus=null;
  let realtimePc=null,realtimeDc=null,realtimeStream=null,realtimeTranscript='',speechRecognition=null,voiceStopTimer=null;
  const show=id=>{views.forEach(view=>$(view).classList.toggle('active',view===id));$('assistantFab').classList.toggle('visible',id==='map');if(id!=='map')closeAssistant();};
  const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const message=(text,type='')=>{const el=$('toast');el.textContent=text;el.className=`toast show ${type}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='toast',4300);};
  const setStatus=(id,text,type='')=>{const el=$(id);el.textContent=text;el.className=`status ${type}`;};
  const announce=text=>{$('screenReaderStatus').textContent='';requestAnimationFrame(()=>$('screenReaderStatus').textContent=text);};
  async function requestJSON(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Something went wrong. Please try again.');return body;}
  const initials=value=>(clean(value||'A').split(/\s+/).map(part=>part[0]).join('').slice(0,2)||'A').toUpperCase();
  function setUser(user){currentUser=user||null;$('userChip').style.display=user?'flex':'none';$('signOut').hidden=!user;if(user){$('userName').textContent=user.name||user.email;$('avatar').textContent=initials(user.name||user.email);}}
  async function hydrate(){const params=new URLSearchParams(location.search),authError=params.get('auth_error');if(authError||params.has('signed_in')||params.has('notion_connected'))history.replaceState({},'',location.pathname);try{const state=await requestJSON('/api/auth/me');setUser(state.user);if(!state.user){show('landing');if(authError==='google_not_configured')setStatus('authStatus','Google sign-in is not enabled in Supabase Auth yet.','error');return;}if(!state.notion){show('connect');return;}show('map');await loadMap();}catch(error){setUser(null);show('landing');message(error.message,'error');}}
  function startGoogle(){const button=$('googleButton');button.disabled=true;setStatus('authStatus','Opening secure Google sign-in…');location.assign('/api/auth/google');}
  async function emailAuth(event,url,signup){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]');button.disabled=true;setStatus('authStatus','Working securely…');try{const values=Object.fromEntries(new FormData(form));const result=await requestJSON(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(values)});if(result.needsEmailConfirmation){setStatus('authStatus','Check your inbox to confirm the account, then sign in.','success');return;}form.reset();await hydrate();message(signup?'Account created. Connect Notion to continue.':'Welcome back.','success');}catch(error){setStatus('authStatus',error.message,'error');}finally{button.disabled=false;}}
  async function signOut(){cancelAssistant();try{await requestJSON('/api/auth/logout',{method:'POST'});}catch{}mapData=null;selectedId=null;setUser(null);show('landing');message('Signed out.');}
  async function disconnect(){if(!confirm('Disconnect Notion from this app? Your workspace will not be read or edited until you reconnect.'))return;try{await requestJSON('/api/auth/notion/disconnect',{method:'POST'});mapData=null;settingsLoaded=false;show('connect');message('Notion disconnected.');}catch(error){message(error.message,'error');}}

  const plain=value=>{if(!value)return '';if(Array.isArray(value))return value.map(item=>item?.plain_text||item?.text?.content||'').join('');if(typeof value==='string')return value;return value?.plain_text||value?.text?.content||'';};
  function propertyValue(value={}){if(value.title)return plain(value.title);if(value.rich_text)return plain(value.rich_text);if(value.select)return value.select?.name||'';if(value.status)return value.status?.name||'';if(value.multi_select)return value.multi_select.map(item=>item.name).join(', ');if(value.date)return [value.date.start,value.date.end].filter(Boolean).join(' — ');if(typeof value.checkbox==='boolean')return value.checkbox?'Checked':'Unchecked';if(value.number!==null&&value.number!==undefined)return String(value.number);if(value.url)return value.url;if(value.email)return value.email;if(value.phone_number)return value.phone_number;if(value.people)return value.people.map(person=>person.name||person.id).join(', ');if(value.relation)return `${value.relation.length} linked`;if(value.formula)return propertyValue(value.formula[value.formula.type]);if(value.rollup)return propertyValue(value.rollup[value.rollup.type]);if(value.files)return value.files.map(file=>file.name||file.external?.url||file.file?.url||'').filter(Boolean).join(', ');return '';}
  function childIds(node){const direct=node?.children||[],rowChildren=node?.type==='database'?(node.database?.rows||[]).flatMap(rowId=>mapData?.nodes[rowId]?.children||[]):[];return [...new Set([...direct,...rowChildren])].filter(id=>mapData?.nodes[id]?.title);}
  const contentText=entries=>(entries||[]).map(entry=>[entry.text,contentText(entry.children)].filter(Boolean).join(' ')).join(' ');
  function searchableText(node){const rows=(node?.database?.rows||[]).map(id=>{const row=mapData.nodes[id];return [row?.title,...Object.values(row?.properties||{}).map(propertyValue),contentText(row?.content)].join(' ');}).join(' ');return [node?.title,node?.type,contentText(node?.content),...Object.keys(node?.database?.properties||{}),rows].join(' ').toLowerCase();}
  function subtreeHasMatch(id,term,seen=new Set()){if(seen.has(id))return false;seen.add(id);const node=mapData?.nodes[id];return Boolean(node&&(searchableText(node).includes(term)||childIds(node).some(child=>subtreeHasMatch(child,term,seen))));}
  function databaseTable(node,className='node-table'){const columns=Object.keys(node?.database?.properties||{}),rows=(node?.database?.rows||[]).map(id=>mapData.nodes[id]).filter(Boolean);if(!columns.length||!rows.length)return null;const wrap=document.createElement('div');wrap.className=className;const table=document.createElement('table'),thead=document.createElement('thead'),head=document.createElement('tr');columns.forEach(name=>{const th=document.createElement('th');th.textContent=name;head.append(th);});thead.append(head);table.append(thead);const body=document.createElement('tbody');rows.forEach(row=>{const tr=document.createElement('tr');tr.tabIndex=0;tr.title='Open this row’s approved Notion content';const selectRow=event=>{if(event.target.closest('a'))return;selectedId=row.id;renderDetail();renderMap();};tr.addEventListener('click',selectRow);tr.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectRow(event);}});columns.forEach((name,index)=>{const td=document.createElement('td'),value=index===0?(row.title||propertyValue(row.properties?.[name])):propertyValue(row.properties?.[name]);if(index===0&&row.url){const link=document.createElement('a');link.href=row.url;link.target='_blank';link.rel='noreferrer';link.textContent=value||'Open in Notion';td.append(link);}else td.textContent=value||'—';tr.append(td);});body.append(tr);});table.append(body);wrap.append(table);return wrap;}
  const mapNodeSpan=id=>mapData?.nodes[id]?.type==='database'?(openDatabaseTables.has(id)?3.9:1.15):1;
  const mapNodeWidth=id=>mapData?.nodes[id]?.type==='database'?(openDatabaseTables.has(id)?790:300):270;
  function mapLayout(rootId,term){const positions={},links=[],childrenById=new Map(),widths=[],left=32,top=36,unit=112;let cursor=0;function collect(id,depth){const node=mapData.nodes[id];if(!node?.title)return;const children=(term||expanded.has(id))?childIds(node).filter(child=>!term||subtreeHasMatch(child,term)):[];childrenById.set(id,children);widths[depth]=Math.max(widths[depth]||0,mapNodeWidth(id));children.forEach(child=>collect(child,depth+1));}collect(rootId,0);const depthX=[];let nextX=left;widths.forEach((width,depth)=>{depthX[depth]=nextX;nextX+=(width||270)+44;});function visit(id,depth){const node=mapData.nodes[id];if(!node?.title)return 0;const children=childrenById.get(id)||[],own=mapNodeSpan(id),start=cursor;if(!children.length){positions[id]={x:depthX[depth],y:top+start*unit,width:mapNodeWidth(id),depth};cursor+=own;return own;}let childrenSpan=0;children.forEach(child=>{links.push([id,child]);childrenSpan+=visit(child,depth+1);});const span=Math.max(own,childrenSpan);if(span>childrenSpan)cursor+=span-childrenSpan;positions[id]={x:depthX[depth],y:top+(start+Math.max(0,(span-own)/2))*unit,width:mapNodeWidth(id),depth};return span;}visit(rootId,0);return {positions,links,height:Math.max(820,top+cursor*unit+120),width:Math.max(1800,nextX+40)};}
  function renderMapCard(id,position,term){const node=mapData.nodes[id],children=childIds(node),isDatabase=node.type==='database',tableOpen=isDatabase&&openDatabaseTables.has(id),card=document.createElement('article');card.className=`map-node ${isDatabase?'database':''} ${tableOpen?'table-open':''} ${!isDatabase&&children.length?'branch':'page'} ${id===mapData.rootNodeId?'root':''} ${id===selectedId?'selected':''}`;card.dataset.nodeId=id;card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`${node.title}${children.length?`, ${children.length} child items`:''}`);card.style.left=`${position.x}px`;card.style.top=`${position.y}px`;const header=document.createElement('div');header.className='map-node-head';const icon=document.createElement('span');icon.className='node-icon';icon.textContent=isDatabase?'DB':id===mapData.rootNodeId?'OS':'P';const title=document.createElement('span');title.className='map-node-title';title.textContent=node.title;header.append(icon,title);if(children.length){const toggle=document.createElement('button');toggle.type='button';toggle.className='map-node-toggle';toggle.dataset.toggle=id;toggle.setAttribute('aria-label',expanded.has(id)?'Collapse subpages':'Expand subpages');toggle.textContent=(term||expanded.has(id))?'−':'+';header.append(toggle);}card.append(header);const rows=node.database?.rows?.length||0,meta=document.createElement('p');meta.className='map-node-meta';meta.textContent=isDatabase?`${rows} live rows${tableOpen?' — table open':' — click to open'}`:children.length?`${children.length} subpages`:'Notion page';card.append(meta);if(isDatabase){const toggle=document.createElement('button');toggle.type='button';toggle.className='map-node-table-toggle';toggle.dataset.tableToggle=id;toggle.textContent=tableOpen?'Hide live table':'Open live table';card.append(toggle);if(tableOpen){const table=databaseTable(node);if(table)card.append(table);}}const activate=event=>{const tableToggle=event.target.closest('[data-table-toggle]');if(tableToggle){openDatabaseTables.has(id)?openDatabaseTables.delete(id):openDatabaseTables.add(id);selectedId=id;renderMap();renderDetail();return;}const branchToggle=event.target.closest('[data-toggle]');if(branchToggle){expanded.has(id)?expanded.delete(id):expanded.add(id);renderMap();renderDetail();return;}if(event.target.closest('a'))return;selectedId=id;if(isDatabase)openDatabaseTables.add(id);else if(children.length&&!term){expanded.has(id)?expanded.delete(id):expanded.add(id);}renderMap();renderDetail();};card.addEventListener('click',activate);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();activate(event);}});return card;}
  function renderMap(){const canvas=$('canvas');if(!mapData)return;const rootId=mapData.rootNodeId,term=$('mapSearch').value.trim().toLowerCase();if(!rootId||!mapData.nodes[rootId]){canvas.innerHTML='<div class="map-empty"><h2>No approved Notion pages were found</h2><p>Share a page or database with your Notion integration, then refresh.</p></div>';return;}const layout=mapLayout(rootId,term);canvas.innerHTML='';const stage=document.createElement('div');stage.className='map-stage';stage.style.width=`${layout.width}px`;stage.style.height=`${layout.height}px`;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('map-svg');svg.setAttribute('width',layout.width);svg.setAttribute('height',layout.height);layout.links.forEach(([from,to])=>{const a=layout.positions[from],b=layout.positions[to];if(!a||!b)return;const fromHeight=Math.min(mapNodeSpan(from)*112,openDatabaseTables.has(from)?330:88),toHeight=Math.min(mapNodeSpan(to)*112,openDatabaseTables.has(to)?330:88),startY=a.y+fromHeight/2,endY=b.y+toHeight/2,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${a.x+a.width} ${startY} C ${a.x+a.width+42} ${startY}, ${b.x-42} ${endY}, ${b.x} ${endY}`);path.setAttribute('fill','none');path.setAttribute('stroke','#79b8ff99');path.setAttribute('stroke-width','2');svg.append(path);});stage.append(svg);Object.entries(layout.positions).forEach(([id,position])=>stage.append(renderMapCard(id,position,term)));canvas.append(stage);}
  function appendPageContent(container,entries,depth=0){for(const entry of entries||[]){const label=entry.text||(entry.url?entry.type.replace(/_/g,' '):'');if(label){const line=document.createElement('div');line.textContent=`${entry.type==='to_do'?(entry.checked?'☑ ':'☐ '):''}${label}`;line.style.cssText=`white-space:pre-wrap;margin:${entry.type.startsWith('heading')?'13px':'7px'} 0 0 ${Math.min(depth,5)*13}px;font-weight:${entry.type.startsWith('heading')?'750':'400'};color:${entry.type.startsWith('heading')?'#eff5ff':'#cbd8ed'}`;container.append(line);}if(entry.url){const link=document.createElement('a');link.href=entry.url;link.target='_blank';link.rel='noreferrer';link.textContent=entry.url;link.style.cssText=`display:block;margin:4px 0 0 ${Math.min(depth,5)*13}px;color:var(--cyan);font-size:12px;overflow-wrap:anywhere`;container.append(link);}appendPageContent(container,entry.children,depth+1);}}
  function renderDetail(){const panel=$('detail'),node=mapData?.nodes[selectedId];panel.innerHTML='';if(!node){panel.innerHTML='<h2>Select an item</h2><p class="muted">Choose a real page or database from your Notion structure.</p>';return;}const title=document.createElement('h2');title.textContent=node.title||'Untitled row';const subtitle=document.createElement('p');subtitle.className='muted';subtitle.textContent=node.type==='database'?'Live database table':node.type==='database_row'?'Database row':node.type==='root'?'Your approved Notion workspace':'Notion page';panel.append(title,subtitle);if(node.url){const link=document.createElement('a');link.className='open-link';link.href=node.url;link.target='_blank';link.rel='noreferrer';link.textContent='Open in Notion ↗';panel.append(link);}if(node.type==='database'){const table=databaseTable(node,'table-wrap');if(table)panel.append(table);}if(node.content?.length){const heading=document.createElement('h3');heading.textContent='Page content';const content=document.createElement('div');content.className='table-wrap';content.style.padding='12px';appendPageContent(content,node.content);panel.append(heading,content);}}
  function renderStats(){const stats=mapData.stats||{},liveRows=Object.values(mapData.nodes||{}).filter(node=>node.type==='database').reduce((total,node)=>total+(node.database?.rows||[]).filter(id=>mapData.nodes[id]).length,0);$('workspaceTitle').textContent=`${mapData.workspace||'Notion'} command map`;$('mapSubtitle').textContent=mapData.partial?'The scan completed with limited access to one or more shared items.':'Only real, titled content shared with this integration.';$('stats').replaceChildren(...[['Pages',stats.pages||0],['Databases',stats.databases||0],['Table rows',liveRows]].map(([label,value])=>{const div=document.createElement('div');div.className='metric';div.innerHTML=`<span>${label}</span><b>${value}</b>`;return div;}));$('syncTime').textContent=`Live scan refreshed ${mapData.scannedAt?new Date(mapData.scannedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'now'}${mapData.scanErrors?` · ${mapData.scanErrors} item(s) could not be read`:''}.`;}
  async function loadMap(){const canvas=$('canvas'),previous=mapData;canvas.innerHTML='<div class="map-empty"><span class="loading"></span>Building your live Notion structure…</div>';try{mapData=await requestJSON('/api/notion/map');expanded=new Set([mapData.rootNodeId]);openDatabaseTables.clear();selectedId=mapData.rootNodeId;renderStats();renderMap();renderDetail();return true;}catch(error){mapData=previous;if(previous)renderMap();else canvas.innerHTML=`<div class="map-empty"><h2>Could not load your Notion map</h2><p>${escapeHtml(error.message)}</p></div>`;message(error.message,'error');return false;}}
  async function refreshMap(){const button=$('refreshMap');button.disabled=true;button.textContent='Refreshing…';try{if(await loadMap())message('Live map refreshed from Notion.','success');}finally{button.disabled=false;button.textContent='Refresh live map';}}

  function setAssistantState(value){$('assistantState').textContent=value;announce(value);}
  function setBusy(value){assistantBusy=value;$('sendCommand').disabled=value;$('micButton').disabled=value;$('cancelCommand').disabled=!value;$('commandInput').disabled=value;}
  function addProgress(text){const item=document.createElement('li');item.textContent=text;$('assistantProgress').append(item);item.scrollIntoView({block:'nearest'});}
  function addMessage(role,text,{actions=[]}={}){const item=document.createElement('article');item.className=`message ${role}`;const body=document.createElement('div');body.textContent=text;item.append(body);if(actions.length){const links=document.createElement('div');links.className='message-links';actions.forEach(action=>{if(action.targetUrl){const link=document.createElement('a');link.href=action.targetUrl;link.target='_blank';link.rel='noreferrer';link.textContent=action.targetTitle||'Open in Notion';links.append(link);}if(action.undoAvailable&&action.actionId){const undo=document.createElement('button');undo.type='button';undo.className='undo';undo.textContent='Undo';undo.addEventListener('click',()=>undoAction(action.actionId,undo));links.append(undo);}});item.append(links);}$('assistantMessages').append(item);item.scrollIntoView({behavior:'smooth',block:'nearest'});return item;}
  function speak(text){if($('muteResponse').checked||!$('voicePreference').checked||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=/[\u0900-\u097F]/.test(text)?'hi-IN':'en-IN';utterance.rate=1;window.speechSynthesis.speak(utterance);}
  function renderConfirmation(event){const host=$('confirmationHost');host.innerHTML='';const box=document.createElement('section');box.className='confirmation';box.innerHTML=`<h3>Confirm this Notion change</h3><p>${escapeHtml(event.plan.summary)}</p><p>${escapeHtml(event.plan.reason)}</p>`;const actions=document.createElement('div');actions.className='confirmation-actions';const confirmButton=document.createElement('button');confirmButton.className='button primary small';confirmButton.type='button';confirmButton.textContent='Confirm';const cancelButton=document.createElement('button');cancelButton.className='button ghost small';cancelButton.type='button';cancelButton.textContent='Cancel';confirmButton.addEventListener('click',()=>{host.innerHTML='';runStream('confirm',{confirmationToken:event.confirmationToken});});cancelButton.addEventListener('click',()=>{host.innerHTML='';setAssistantState('Cancelled');addMessage('assistant','Cancelled. Nothing was changed.');setBusy(false);});actions.append(confirmButton,cancelButton);box.append(actions);host.append(box);setAssistantState('Waiting for confirmation');confirmButton.focus();}
  function handleAssistantEvent(event){if(event.type==='session_started'){setAssistantState('Understanding request');addProgress('Secure assistant session started.');}else if(event.type==='intent_detected'){addProgress(`Understood: ${event.summary}`);}else if(event.type==='tool_started'){setAssistantState(event.label);addProgress(event.label);}else if(event.type==='tool_completed'){addProgress(`${event.label} — complete`);}else if(event.type==='confirmation_required'){renderConfirmation(event);}else if(event.type==='action_completed'){setAssistantState('Completed');const summary=event.result?.summary||'Done.';addMessage('assistant',summary,{actions:event.result?.actions||[]});speak(summary);if((event.result?.actions||[]).length)loadMap();loadHistory();}else if(event.type==='action_failed'){setAssistantState('Error');const partial=event.partialActions?.length?' Some earlier changes may have completed; review the links above.':'';addMessage('error',`${event.message}${partial}`,{actions:event.partialActions||[]});}else if(event.type==='session_completed'){if(!document.querySelector('.confirmation'))setBusy(false);}}
  async function runStream(action,body){if(activeController)activeController.abort();activeController=new AbortController();setBusy(true);$('assistantProgress').innerHTML='';try{const response=await fetch(`/api/assistant?action=${encodeURIComponent(action)}`,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','accept':'text/event-stream'},body:JSON.stringify(body),signal:activeController.signal});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||'The assistant request failed.');}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const data=block.split('\n').filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trim()).join('');if(data)handleAssistantEvent(JSON.parse(data));}if(done)break;}}catch(error){if(error.name==='AbortError'){setAssistantState('Cancelled');addMessage('assistant','Cancelled. I stopped waiting for this command.');}else{setAssistantState('Error');addMessage('error',error.message||'The assistant failed safely.');}setBusy(false);}finally{activeController=null;}}
  function sendCommand(){const command=clean($('commandInput').value);if(!command||assistantBusy)return;addMessage('user',command);$('commandInput').value='';runStream('run',{command,inputType:$('commandInput').dataset.inputType||'text'});$('commandInput').dataset.inputType='text';}
  function cancelAssistant(){discardRecording=true;if(recorder&&recorder.state!=='inactive')recorder.stop();mediaStream?.getTracks().forEach(track=>track.stop());mediaStream=null;clearInterval(recordingTimer);speechRecognition?.abort?.();speechRecognition=null;destroyRealtime();if(activeController)activeController.abort();setBusy(false);}
  function resetVoiceUi(){clearTimeout(voiceStopTimer);$('micButton').classList.remove('listening');$('stopRecording').hidden=true;$('recordingTime').textContent='';$('voiceNote').textContent='Tap the microphone, or type below.';}
  function destroyRealtime(){realtimeDc?.close?.();realtimePc?.close?.();realtimeStream?.getTracks().forEach(track=>track.stop());realtimeDc=null;realtimePc=null;realtimeStream=null;resetVoiceUi();}
  function commitLiveVoice(){if(speechRecognition){speechRecognition.stop();return;}if(!realtimePc)return;realtimeStream?.getTracks().forEach(track=>track.stop());if(realtimeDc?.readyState==='open')realtimeDc.send(JSON.stringify({type:'input_audio_buffer.commit'}));setAssistantState('Finishing transcript');$('voiceNote').textContent='Finishing your command…';voiceStopTimer=setTimeout(()=>{const transcript=clean(realtimeTranscript||$('commandInput').value);destroyRealtime();if(transcript){$('commandInput').value=transcript;$('commandInput').dataset.inputType='voice';sendCommand();}else addMessage('error','I could not hear a usable command. Try again or type it.');},5000);}
  function startBrowserSpeechFallback(reason=''){
    const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){if(reason)addMessage('error',`${reason} Using the recorded-audio fallback.`);startRecording();return;}
    const recognition=new Recognition();speechRecognition=recognition;recognition.continuous=false;recognition.interimResults=true;recognition.lang='en-IN';realtimeTranscript='';
    recognition.onstart=()=>{resetVoiceUi();$('micButton').classList.add('listening');$('stopRecording').hidden=false;$('voiceNote').textContent='Listening live…';setAssistantState('Listening live');};
    recognition.onresult=event=>{let transcript='';for(let index=event.resultIndex;index<event.results.length;index++)transcript+=event.results[index][0]?.transcript||'';realtimeTranscript=clean(`${realtimeTranscript} ${transcript}`);$('commandInput').value=realtimeTranscript;setAssistantState('Hearing your command');};
    recognition.onerror=event=>{speechRecognition=null;resetVoiceUi();setAssistantState('Voice unavailable');addMessage('error',event.error==='not-allowed'?'Microphone permission was denied. Allow it in browser settings or type your command.':reason||'Live voice could not understand that. Try again.');};
    recognition.onend=()=>{speechRecognition=null;resetVoiceUi();const transcript=clean(realtimeTranscript||$('commandInput').value);if(transcript){$('commandInput').value=transcript;$('commandInput').dataset.inputType='voice';sendCommand();}else setAssistantState('Ready');};
    try{recognition.start();}catch{speechRecognition=null;startRecording();}
  }
  async function startLiveVoice(){
    if(assistantBusy)return;if(realtimePc||speechRecognition){commitLiveVoice();return;}
    if(!window.RTCPeerConnection||!navigator.mediaDevices?.getUserMedia){startBrowserSpeechFallback();return;}
    try{
      realtimeTranscript='';const pc=new RTCPeerConnection();realtimePc=pc;const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1}});realtimeStream=stream;pc.addTrack(stream.getAudioTracks()[0]);
      const dc=pc.createDataChannel('oai-events');realtimeDc=dc;
      dc.addEventListener('message',event=>{let data;try{data=JSON.parse(event.data);}catch{return;}
        if(data.type==='conversation.item.input_audio_transcription.delta'){realtimeTranscript+=data.delta||'';$('commandInput').value=realtimeTranscript;setAssistantState('Hearing your command');}
        else if(data.type==='conversation.item.input_audio_transcription.completed'){clearTimeout(voiceStopTimer);const transcript=clean(data.transcript||realtimeTranscript);destroyRealtime();if(!transcript){addMessage('error','I could not hear a usable command. Try again or type it.');return;}$('commandInput').value=transcript;$('commandInput').dataset.inputType='voice';setAssistantState('Working');sendCommand();}
        else if(data.type==='input_audio_buffer.speech_started')setAssistantState('Listening live');
        else if(data.type==='input_audio_buffer.speech_stopped')setAssistantState('Finishing transcript');
        else if(data.type==='error'){const messageText=data.error?.message||'Live voice encountered an error.';destroyRealtime();startBrowserSpeechFallback(messageText);}
      });
      const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await fetch('/api/assistant?action=realtime',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/sdp'},body:offer.sdp});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||'OpenAI live voice could not start.');}await pc.setRemoteDescription({type:'answer',sdp:await response.text()});
      resetVoiceUi();$('micButton').classList.add('listening');$('stopRecording').hidden=false;$('voiceNote').textContent='Listening live — pause when finished.';setAssistantState('Listening live');
    }catch(error){destroyRealtime();if(error.name==='NotAllowedError'){setAssistantState('Permission required');addMessage('error','Microphone permission was denied. Allow it in browser settings or type your command.');return;}startBrowserSpeechFallback(error.message);}
  }
  const supportedMime=()=>['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/mp4'].find(type=>window.MediaRecorder?.isTypeSupported?.(type))||'';
  const blobBase64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(blob);});
  async function startRecording(){if(assistantBusy||recorder?.state==='recording')return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){addMessage('error','Voice recording is not supported in this browser. Type your command instead.');return;}try{discardRecording=false;mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1}});audioChunks=[];const mime=supportedMime();recorder=new MediaRecorder(mediaStream,mime?{mimeType:mime,audioBitsPerSecond:32000}:{audioBitsPerSecond:32000});recorder.addEventListener('dataavailable',event=>{if(event.data.size)audioChunks.push(event.data);});recorder.addEventListener('stop',finishRecording,{once:true});recordingStarted=Date.now();recorder.start(250);$('micButton').classList.add('listening');$('stopRecording').hidden=false;$('voiceNote').innerHTML='<span class="wave"><i></i><i></i><i></i><i></i></span> Listening…';setAssistantState('Listening');recordingTimer=setInterval(()=>{const seconds=Math.floor((Date.now()-recordingStarted)/1000);$('recordingTime').textContent=`0:${String(seconds).padStart(2,'0')}`;if(seconds>=60)stopRecording();},250);}catch(error){setAssistantState('Permission required');addMessage('error',error.name==='NotAllowedError'?'Microphone permission was denied. Allow it in browser settings or type your command.':'No usable microphone was found. Type your command instead.');}}
  function stopRecording(){if(realtimePc||speechRecognition)return commitLiveVoice();if(recorder?.state==='recording')recorder.stop();}
  async function finishRecording(){clearInterval(recordingTimer);resetVoiceUi();mediaStream?.getTracks().forEach(track=>track.stop());mediaStream=null;if(discardRecording){discardRecording=false;return;}const durationMs=Date.now()-recordingStarted,blob=new Blob(audioChunks,{type:recorder.mimeType||'audio/webm'});if(blob.size<100){addMessage('error','The recording was empty. Try again or type your command.');return;}setAssistantState('Transcribing');setBusy(true);try{const result=await requestJSON('/api/assistant?action=transcribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({audioBase64:await blobBase64(blob),mimeType:blob.type||'audio/webm',durationMs})});$('commandInput').value=result.transcript;$('commandInput').dataset.inputType='voice';setBusy(false);setAssistantState('Working');sendCommand();}catch(error){setAssistantState('Error');addMessage('error',error.message);setBusy(false);}}
  async function undoAction(actionId,button){button.disabled=true;button.textContent='Undoing…';try{const result=await requestJSON('/api/assistant?action=undo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actionId})});button.textContent='Undone';addMessage('assistant',result.message);await loadMap();}catch(error){button.disabled=false;button.textContent='Undo';addMessage('error',error.message);}}
  function candidateOption(item){const option=document.createElement('option');option.value=item.id;option.textContent=`${item.title} (${item.type.replace('_',' ')})`;option.dataset.type=item.type;return option;}
  function setSelectValue(select,value,type){if(value&&!Array.from(select.options).some(option=>option.value===value)){const option=document.createElement('option');option.value=value;option.textContent='Previously saved Notion object';option.dataset.type=type||'';select.append(option);}select.value=value||'';}
  async function loadSettings(){setStatus('settingsStatus','Discovering your approved Notion structure…');try{const data=await requestJSON('/api/assistant?action=settings');for(const id of ['dailySource','mapObject']){const select=$(id),first=select.options[0];select.replaceChildren(first);}data.candidates.forEach(item=>{$('dailySource').append(candidateOption(item));$('mapObject').append(candidateOption(item));});const settings=data.settings||{};setSelectValue($('dailySource'),settings.dailyEntrySourceId,settings.dailyEntrySourceType);setSelectValue($('mapObject'),settings.mapObjectId,settings.mapObjectType);$('dailyDateProperty').value=settings.dailyEntryDateProperty||'';$('dailyTitleProperty').value=settings.dailyEntryTitleProperty||'';$('assistantTimezone').value=settings.timezone||'Asia/Kolkata';$('confirmationPreference').value=settings.confirmationPreference||'risk_based';$('voicePreference').checked=settings.voiceResponsePreference!==false;setStatus('settingsStatus','Discovery complete. Confirm the best matches.','success');settingsLoaded=true;}catch(error){setStatus('settingsStatus',error.message,'error');}}
  async function saveSettings(event){event.preventDefault();const daily=$('dailySource').selectedOptions[0],map=$('mapObject').selectedOptions[0],button=event.currentTarget.querySelector('button[type="submit"]');button.disabled=true;try{await requestJSON('/api/assistant?action=settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dailyEntrySourceId:daily?.value||'',dailyEntrySourceType:daily?.dataset.type||'',dailyEntryDateProperty:$('dailyDateProperty').value,dailyEntryTitleProperty:$('dailyTitleProperty').value,mapObjectId:map?.value||'',mapObjectType:map?.dataset.type||'',timezone:$('assistantTimezone').value,confirmationPreference:$('confirmationPreference').value,voiceResponsePreference:$('voicePreference').checked})});setStatus('settingsStatus','Assistant settings saved.','success');}catch(error){setStatus('settingsStatus',error.message,'error');}finally{button.disabled=false;}}
  async function loadHistory(){try{const data=await requestJSON('/api/assistant?action=history'),host=$('assistantHistory');host.innerHTML='';if(!data.runs.length){host.innerHTML='<p class="muted">No saved commands yet.</p>';return;}data.runs.forEach(run=>{const item=document.createElement('div');item.className='history-item';item.innerHTML=`<b>${escapeHtml(run.original_transcript)}</b>${escapeHtml(run.status)} · ${new Date(run.started_at).toLocaleString()}`;host.append(item);});}catch{}}
  function openAssistant(){lastFocus=document.activeElement;$('assistantBackdrop').hidden=false;$('assistantPanel').hidden=false;document.body.style.overflow='hidden';setAssistantState('Ready');$('commandInput').focus();if(!settingsLoaded){loadSettings();loadHistory();}}
  function closeAssistant(){if(!$('assistantPanel')||$('assistantPanel').hidden)return;cancelAssistant();window.speechSynthesis?.cancel();$('assistantPanel').hidden=true;$('assistantBackdrop').hidden=true;document.body.style.overflow='';lastFocus?.focus?.();}
  function trapFocus(event){if(event.key==='Escape'){closeAssistant();return;}if(event.key!=='Tab')return;const focusable=[...$('assistantPanel').querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[href]')].filter(el=>!el.hidden&&el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  function bind(){$('googleButton').addEventListener('click',startGoogle);$('signupForm').addEventListener('submit',event=>emailAuth(event,'/api/auth/signup',true));$('signinForm').addEventListener('submit',event=>emailAuth(event,'/api/auth/signin',false));$('notionButton').addEventListener('click',()=>{setStatus('connectStatus','Opening Notion’s secure approval screen…');location.assign('/api/auth/notion');});$('refreshMap').addEventListener('click',refreshMap);$('expandAll').addEventListener('click',()=>{Object.values(mapData?.nodes||{}).forEach(node=>{if(node.children?.length)expanded.add(node.id);});renderMap();});$('collapseAll').addEventListener('click',()=>{expanded.clear();openDatabaseTables.clear();selectedId=mapData?.rootNodeId||null;renderMap();renderDetail();});$('mapSearch').addEventListener('input',renderMap);$('signOut').addEventListener('click',signOut);$('disconnectNotion').addEventListener('click',disconnect);$('assistantFab').addEventListener('click',openAssistant);$('assistantClose').addEventListener('click',closeAssistant);$('assistantBackdrop').addEventListener('click',closeAssistant);$('assistantPanel').addEventListener('keydown',trapFocus);$('assistantSettingsButton').addEventListener('click',()=>{$('assistantSettings').open=true;if(!settingsLoaded)loadSettings();$('assistantSettings').scrollIntoView({behavior:'smooth'});});$('micButton').addEventListener('click',startLiveVoice);$('stopRecording').addEventListener('click',stopRecording);$('sendCommand').addEventListener('click',sendCommand);$('commandInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendCommand();}});$('cancelCommand').addEventListener('click',cancelAssistant);$('settingsForm').addEventListener('submit',saveSettings);$('rediscoverSettings').addEventListener('click',()=>{settingsLoaded=false;loadSettings();});window.addEventListener('beforeunload',cancelAssistant);hydrate();}
  window.addEventListener('DOMContentLoaded',bind,{once:true});
})();
